compcat_index:
    path:     /
    defaults: { _controller: "BizzAdminBundle:CompCat:index" }
    methods:  GET

compcat_show:
    path:     /{id}/show
    defaults: { _controller: "BizzAdminBundle:CompCat:show" }
    methods:  GET

compcat_new:
    path:     /new
    defaults: { _controller: "BizzAdminBundle:CompCat:new" }
    methods:  [GET, POST]

compcat_edit:
    path:     /{id}/edit
    defaults: { _controller: "BizzAdminBundle:CompCat:edit" }
    methods:  [GET, POST]

compcat_delete:
    path:     /{id}/delete
    defaults: { _controller: "BizzAdminBundle:CompCat:delete" }
    methods:  DELETE
