countries_index:
    path:     /
    defaults: { _controller: "BizzAdminBundle:Countries:index" }
    methods:  GET

countries_show:
    path:     /{id}/show
    defaults: { _controller: "BizzAdminBundle:Countries:show" }
    methods:  GET

countries_new:
    path:     /new
    defaults: { _controller: "BizzAdminBundle:Countries:new" }
    methods:  [GET, POST]

countries_edit:
    path:     /{id}/edit
    defaults: { _controller: "BizzAdminBundle:Countries:edit" }
    methods:  [GET, POST]

countries_delete:
    path:     /{id}/delete
    defaults: { _controller: "BizzAdminBundle:Countries:delete" }
    methods:  DELETE
