productcategories_index:
    path:     /
    defaults: { _controller: "BizzAdminBundle:ProductCategories:index" }
    methods:  GET

productcategories_show:
    path:     /{id}/show
    defaults: { _controller: "BizzAdminBundle:ProductCategories:show" }
    methods:  GET

productcategories_new:
    path:     /new
    defaults: { _controller: "BizzAdminBundle:ProductCategories:new" }
    methods:  [GET, POST]

productcategories_edit:
    path:     /{id}/edit
    defaults: { _controller: "BizzAdminBundle:ProductCategories:edit" }
    methods:  [GET, POST]

productcategories_delete:
    path:     /{id}/delete
    defaults: { _controller: "BizzAdminBundle:ProductCategories:delete" }
    methods:  DELETE
