# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    my_user_provider.class: Bizz\UserBundle\Security\Core\User\FOSUBUserProvider

services:
    biz.form.registration:
        class: Bizz\UserBundle\Form\RegistrationType
        arguments:
            - %fos_user.model.user.class%
        tags:
            - { name: form.type, alias: biz_user_registration }
    my_user_provider:
            class: "%my_user_provider.class%"
            #this is the place where the properties are passed to the UserProvider - see config.yml
            arguments: [ '@fos_user.user_manager', {linkedin: linkedin_id} ]

    bizz.form.flow.registration:
            class: Bizz\UserBundle\Form\CreateRegistrationFlow
            parent: craue.form.flow