<?php

namespace Bizz\AdminBundle\Repository;

/**
 * CompCatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompCatRepository extends \Doctrine\ORM\EntityRepository
{
}
