<?php

namespace Bizz\AdminBundle\Repository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountriesRepository extends \Doctrine\ORM\EntityRepository
{
}
