<?php

namespace Bizz\AdminBundle\Repository;

/**
 * IcatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IcatRepository extends \Doctrine\ORM\EntityRepository
{
}
