<?php

namespace Bizz\AdminBundle\Repository;

/**
 * UserCatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCatRepository extends \Doctrine\ORM\EntityRepository
{
}
