bizz_admin_states:
    resource: "@BizzAdminBundle/Resources/config/routing/states.yml"
    prefix:   /states

bizz_admin_countries:
    resource: "@BizzAdminBundle/Resources/config/routing/countries.yml"
    prefix:   /countries

bizz_admin_usercat:
    resource: "@BizzAdminBundle/Resources/config/routing/usercat.yml"
    prefix:   /usercat

bizz_admin_category:
    resource: "@BizzAdminBundle/Resources/config/routing/category.yml"
    prefix:   /category

bizz_admin_homepage:
    path:     /
    defaults: { _controller: BizzAdminBundle:Default:index }
